# Generated by Django 4.0.6 on 2022-07-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
