# Generated by Django 4.0.6 on 2022-08-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserSchema',
        ),
    ]
