# Generated by Django 4.0.6 on 2022-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_bookschema_delete_userschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookschema',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
