# Generated by Django 3.2.7 on 2022-08-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bookschema_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSchema',
        ),
    ]
