# Generated by Django 3.2.7 on 2022-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bookschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookschema',
            name='book_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
